# This blueprint not mine, it is from a comment made by "Aubrey, cyber7, hebus, Nov 2025" on
# https://community.home-assistant.io/t/synchronize-the-on-off-state-of-2-entities/259010/87

blueprint:
  name: Synchronize 2 States
  description: Bind two switches together to act in unison (bidirectional safe)
  domain: automation
  input:
    switch_1:
      name: Switch 1
      selector:
        entity:
          domain: switch
    switch_2:
      name: Switch 2
      selector:
        entity:
          domain: switch

variables:
  switches: 
    - !input switch_1
    - !input switch_2

trigger:
  - platform: state
    entity_id: 
      - !input switch_1
      - !input switch_2

mode: queued
max_exceeded: silent

condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'

  - condition: template
    value_template: >
      {{ trigger.to_state.context.parent_id is none or 
         (trigger.to_state.context.id != this.context.id and 
          trigger.to_state.context.parent_id != this.context.id) }}

  - condition: template
    value_template: "{{ trigger.to_state.state in ['on', 'off'] }}"

action:
  - service: >-
      {% if trigger.to_state.state == 'on' %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    data:
      entity_id: >
        {{ expand(switches)
           | selectattr('entity_id', '!=', trigger.entity_id)
           | selectattr('state', '!=', trigger.to_state.state)
           | map(attribute='entity_id')
           | list }}
